name: Publish docs

on:
  push: {branches: main}

permissions:
  pages: write
  id-token: write

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14
          dune-cache: true

      - run: opam install odig
      - run: opam install . --deps-only --with-doc

      - run: opam exec -- dune build @install
      - run: opam exec -- dune install

      - run: opam exec -- odig odoc mra_bi_assembler -v --odoc-theme=odoc.default
        env:
          OPAMCOLOR: never
      - run: |
          cp -rv $(opam exec -- odig cache path)/html ./www

          set -x
          cd www

          cp -v ./*/404.html .
          sed -i.bak 's|<head>|<head><base href="https://katrinafyi.github.io/mra-bi-assembler/mra_bi_assembler/404.html" />|' 404.html

          echo "$CSS" >> ./_odoc-theme/odoc.css

        working-directory: _build
        env:
          CSS: |
            h1 nav {
              display: inline;
              font-size: 18px;
              font-weight: normal;
            }
            h1 .version {
              font-size: 18px;
            }
            h1 nav > * {
              margin-left: 10px;
            }

      - id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/www

  docs-publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs-build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
