name: Publish docs

on:
  push: {branches: main}

permissions:
  pages: write
  id-token: write

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14

      - run: opam install . --deps-only --with-doc
      - run: opam exec -- dune build @doc

      - id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/default/_doc/_html

  docs-publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
